###GET ALL IMAGES
GET http://localhost:3000/images


###GET an IMAGE BY ID
GET http://localhost:3000/images/6744541cc0ebd9473685385f


###UPLOAD URL DIRECTLY
POST http://localhost:3000/images
Content-Type: application/json

{
  "imageUrl": "testing"
}

###DELETE IMAGE BY ID
DELETE http://localhost:3000/images/672403ad5af7601804a7da51

###UPLOAD IMAGE INTO LOCAL AND SAVE THE URL INTO DATABASE
POST http://localhost:3000/images/upload
Content-Type: application/json

{
    "filePath": "/home/aydin/Pictures/no9WU.png"
}


### Register User
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "firstName": "dummy-first",
    "lastName": "dummy-last",
    "email": "dummy@gmail.com",
    "password": "admin123"
}

### LOGIN USER
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "admin123"
}


### GET ALL USER USER
GET http://localhost:3000/users/all


### CHANGE STARRED STATUS
PATCH http://localhost:3000/images/6725d3e96c43c0dc10e711f7/star
Content-Type: application/json

{
    "starred": true
}