###GET ALL IMAGES
GET http://localhost:3000/images


###GET an IMAGE BY ID
GET http://localhost:3000/images/672403ad5af7601804a7da51


###UPLOAD URL DIRECTLY
POST http://localhost:3000/images
Content-Type: application/json

{
  "imageUrl": "testing"
}

###DELETE IMAGE BY ID
DELETE http://localhost:3000/images/6720c3add5befc4dba364d4c

###UPLOAD IMAGE INTO IMAGEKIT AND SAVE THE URL INTO DATABASE
POST http://localhost:3000/images/upload
Content-Type: application/json

{
    "filePath": "/home/aydin/Pictures/Screenshot_2024-10-26_16_23_46.png"
}


### Register User
POST http://localhost:3000/users/register
Content-Type: application/json

{ 
    "firstName": "awalan",
    "lastName": "akhiran",
    "email": "test2@example.com",
    "password": "admin123"
}

### LOGIN USER
POST http://localhost:3000/users/login
Content-Type: application/json

{ 
    "email": "test3@example.com",
    "password": "admin123"
}


### GET ALL USER USER
GET http://localhost:3000/users/all
