###GET ALL IMAGES
GET http://localhost:3000/images


###GET an IMAGE BY ID
GET http://localhost:3000/images/672403ad5af7601804a7da51


###UPLOAD URL DIRECTLY
POST http://localhost:3000/images
Content-Type: application/json

{
  "imageUrl": "testing"
}

###DELETE IMAGE BY ID
DELETE http://localhost:3000/images/6721176ca2d8305feeb6ac57

###UPLOAD IMAGE INTO IMAGEKIT AND SAVE THE URL INTO DATABASE
POST http://localhost:3000/images/upload
Content-Type: application/json

{
    "filePath": "/home/mbsaloka/Downloads/chall.jpg"
}


### Register User
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "firstName": "dummy-first",
    "lastName": "dummy-last",
    "email": "dummy@gmail.com",
    "password": "admin123"
}

### LOGIN USER
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "dummy@gmail.com",
    "password": "admin123"
}


### GET ALL USER USER
GET http://localhost:3000/users/all


### CHANGE STARRED STATUS
PATCH http://localhost:3000/images/67298d09d0f7d716abef5292/star
Content-Type: application/json

{
    "starred": true
}